src/python_django_app/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('index/', views.IndexView.as_view(), name='index'),
    path('diary/create/', views.DiaryCreateView.as_view(), name='diary_create'),
    path('diary/create/complete/', views.DiaryCreateCompleteView.as_view(), name='diary_create_complete'),
    path('diary/list/', views.DiaryListView.as_view(), name='diary_list'),
    path('diary/detail/<uuid:pk>/', views.DiaryDetailView.as_view(), name='diary_detail'),
    path('diary/update/<uuid:pk>/', views.DiaryUpdateView.as_view(), name='diary_update'),
    path('diary/delete/<uuid:pk>/', views.DiaryDeleteView.as_view(), name='diary_delete'),
]

src/python_django_app/python_django_app/urls.py
from django.contrib import admin
from django.urls import include, path # 追加：includeをimport

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('diary.urls')), # 追加：includeメソッドでurl設定を追加
]

src/python_django_app/diary/models.py
from django.db import models
from django.utils import timezone
import uuid


class Diary(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date = models.DateField(verbose_name='日付', default=timezone.now)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    text = models.CharField(verbose_name='本文', max_length=200)
    created_at = models.DateTimeField(verbose_name='作成日時', default=timezone.now)
    updated_at = models.DateTimeField(verbose_name='編集日時', blank=True, null=True)

src/python_django_app/diary/forms.py
from django import forms
from .models import Diary

class DiaryForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('date', 'title', 'text',)

src/python_django_app/diary/views.py
from django.views.generic import TemplateView, CreateView, ListView, DetailView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import DiaryForm
from .models import Diary
from django.utils import timezone

class IndexView(TemplateView):
    template_name = 'index.html'

class DiaryCreateView(CreateView):
    template_name = 'diary_create.html'
    form_class = DiaryForm
    success_url = reverse_lazy('diary:diary_create_complete')

class DiaryCreateCompleteView(TemplateView):
    template_name = 'diary_create_complete.html'

class DiaryListView(ListView):
    template_name = 'diary_list.html'
    model = Diary

class DiaryDetailView(DetailView):
    template_name = 'diary_detail.html'
    model = Diary

class DiaryUpdateView(UpdateView):
    template_name = 'diary_update.html'
    model = Diary
    fields = ('date', 'title', 'text',)
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.updated_at = timezone.now()
        diary.save()
        return super().form_valid(form)

class DiaryDeleteView(DeleteView):
    template_name = 'diary_delete.html'
    model = Diary
    success_url = reverse_lazy('diary:diary_list')

src/python_django_app/templates/diary_create.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>MyDiaryApp</title>
  </head>
  <body>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <button type="submit">投稿</button>
    </form>
    <a href="{% url 'diary:index' %}">TOPに戻る</a>
  </body>
</html>

src/python_django_app/templates/diary_create_complete.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>MyDiaryApp</title>
  </head>
  <body>
    <p>日記の投稿が完了しました！</p>
    <a href="{% url 'diary:index' %}">TOPに戻る</a>
  </body>
</html>

src/python_django_app/templates/diary_delete.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>MyDiaryApp</title>
  </head>
  <body>
    <h1>日記の削除</h1>
    <form method="post">
      {% csrf_token %}
      <p>{{ diary.date }} {{ diary.title }} を削除します</p>
      <input type="submit" value="削除" />
    </form>
    <a href="{% url 'diary:diary_list' %}">一覧に戻る</a>
  </body>
</html>

src/python_django_app/templates/diary_detail.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>MyDiaryApp</title>
  </head>
  <body>
    <p>{{ diary.date }}</p>
    <p>{{ diary.title }}</p>
    <p>{{ diary.text }}</p>
    <a href="{% url 'diary:diary_list' %}">一覧に戻る</a> /
    <a href="{% url 'diary:diary_update' diary.pk %}">編集</a> /
    <a href="{% url 'diary:diary_delete' diary.pk %}">削除</a>
  </body>
</html>

src/python_django_app/templates/diary_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>MyDiaryApp</title>
  </head>
  <body>
    {% for diary in diary_list %}
    <p>
      {{ diary.date }}
      <a href="{% url 'diary:diary_detail' diary.pk %}">{{ diary.title }}</a> /
      <a href="{% url 'diary:diary_update' diary.pk %}">編集</a> /
      <a href="{% url 'diary:diary_delete' diary.pk %}">削除</a>
    </p>
    {% endfor %}
    <a href="{% url 'diary:index' %}">TOPに戻る</a>
  </body>
</html>

src/python_django_app/templates/diary_update.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>MyDiaryApp</title>
  </head>
  <body>
    <h1>日記の編集</h1>
    <form method="post">
      {% csrf_token %} {{ form.as_p }}
      <input type="submit" value="保存" />
    </form>
    <a href="{% url 'diary:diary_list' %}">一覧に戻る</a>
  </body>
</html>

src/python_django_app/templates/index.html
<!DOCTYPE html>
<html lang="ja">
  <head>
    <meta charset="UTF-8" />
    <title>MyDiaryApp</title>
  </head>
  <body>
    <h1>Diary App by Django</h1>
    <h2><a href="{% url 'diary:diary_create' %}">日記の投稿</a></h2>
    <h2><a href="{% url 'diary:diary_list' %}">日記の一覧</a></h2>
  </body>
</html>